Repository canonical-web-and-design/www.canonical.com, pull requests merged in 2018-05, with the labels that each got.

#264 Update to Vanilla 1.7.0
  package.json
  static/sass/_pattern_link.scss
  static/sass/styles.scss
  templates/_base/base.html
  templates/about/index.html
  templates/index.html
  templates/partners/index.html
  templates/products/index.html
  templates/services/index.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Status: Review

#273 Update ./run, use talisker in Dockerfile
  .env
  Dockerfile
  package.json
  requirements.txt
  run
Labels: Review: Code +1, Review: QA +1

#274 Bump global nav version
  package.json
  templates/_includes/extended-footer.html
  templates/about/index.html
  templates/services/index.html
  webapp/templatetags/utils.py
  yarn.lock
Labels: Review: Code needed, Review: QA needed
