Repository canonical-web-and-design/www.canonical.com, pull requests merged in 2018-03, with the labels that each got.

#243 Remove Mike Bell from about section
  templates/about/index.html
Labels: Review UX +1, Review: Code +1, Review: QA +1

#247 Update to latest version of run script
  .gitignore
  .sass-lint.yml
  bower.json
  package.json
  run
  static/sass/styles.scss
  templates/500.html
  templates/_base/base.html
  webapp/views.py
  webapp/wsgi.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#249 Update global nav
  package.json
Labels: Review: Code needed, Review: QA needed

#246 Add contact link to footer
  static/sass/styles.scss
  templates/_base/footer.html
Labels: Review UX +1, Review: Code +1, Review: QA +1

#250 Fix typos on services page
  templates/services/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#251 Update copyright notice in footer
  templates/_base/footer.html
Labels: Review: Code +1, Review: QA +1

#253 webteam tooling v3.0.1 and talisker
  .env
  .gitignore
  .sass-lint.yml
  package.json
  requirements.txt
  run
Labels: Review: Code +1, Review: QA +1

#252 Update feeds
  requirements.txt
  templates/_includes/article-items.html
  templates/about/index.html
  webapp/settings.py
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: QA +1

#259 Point careers feed through proxy
  run
  webapp/templatetags/raw_feeds.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1
