Repository canonical-web-and-design/www.canonical.com, pull requests merged in 2019-03, with the labels that each got.

#346 Copyright 2019
  templates/_base/footer.html
Labels: Review: Code +1

#347 Add resolutions for critical vulnerabilities
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#350 Update /services/contact-us
  templates/services/contact-us.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#352 Update footer
  templates/_base/footer.html
Labels: Review: Code +1, Review: QA +1

#353 Remove unused dependencies
  requirements.txt
Labels: Review: Code +1, Review: QA +1
